    <!-- Document Wrapper [Animates fadein fadeout]  is it needed? 
    ============================================= -->
    

        <!-- Header
        ============================================= -->
        <header id="header" class="sticky-style-2">

            <div class="container clearfix header" style="margin-left:auto !important;">

                <!-- Logo
                ============================================= -->
                <div id="logo" class="divcenter">
                    <a href="#" class="standard-logo"><img class="divcenter" src="include/pictures/logo-title.png" alt="Mergeomics Logo"></a>
                    
                 <a href="#" class="retina-logo"><img class="divcenter" src="include/pictures/logo-title.png" alt="Mergeomics Logo"></a> 
                </div><!-- #logo end -->

            </div>

            <div id="header-wrap">

                <!-- Primary Navigation
                ============================================= -->
            

               
                <nav id="primary-menu" class="with-arrows style-2 center">

                    <div class="container clearfix header" style="margin-left:auto !important;">

                        <div id="primary-menu-trigger"><i class="icon-reorder"></i></div>

                        <ul>
                            <li class="current"><a href="#"><div>Home</div></a></li>
                            <li><a href="runmergeomics.php"><div>Run Mergeomics</div></a></li>
                            <li><a href="runpharmomics.php"><div>Run PharmOmics</div></a></li>
                            <!--<li><a href="runtoxiomics.php"><div>Run Toxiomics</div></a></li>-->
                            <li><a href="tutorial.php"><div>Tutorial</div></a>
                                <ul>
                                    <!--<li><a href="#" title=""><div>In production!</div></a></li>-->
                                    <!--<li><a href="tutorial_MDF.php" title=""><div>MDF</div></a></li>-->
                                    <!--<li><a href="tutorial_MSEA.php" title=""><div>MSEA</div></a></li>-->
                                    <!--<li><a href="tutorial_Meta.php" title=""><div>Meta MSEA</div></a></li>-->
                                    <!--<li><a href="tutorial_KDA.php" title=""><div>wKDA</div></a></li>-->
                                    <!--<li><a href="tutorial_vis.php" title=""><div>Visualization</div></a></li>-->
                                    <!--<li><a href="tutorial_data.php" title=""><div>Additional Data Types</div></a></li>-->
                                    <!--<li><a href="tutorial_PharmOmics.php" title=""><div>PharmOmics</div></a></li>-->
                                    <li><a href="tutorial.php" title=""><div>Mergeomics</div></a></li>
                                    <li><a href="tutorial_pharmomics.php" title=""><div>Pharmomics</div></a></li>
                                </ul>
                            </li>
                            <li><a href="contact.php"><div>Contact</div></a></li>
                      </div>

                </nav>

        </div>
</header>





<!-- Old navigation

     <li class="current"><a href="home.php"><div>Home</div></a></li>
                            <li><a href="tutorial.php"><div>Tutorial</div></a>
                                <ul>
                                    <li><a href="tutorial.php" title=""><div>Overview</div></a></li>
                                    <li><a href="tutorial_MDF.php" title=""><div>MDF</div></a></li>
                                    <li><a href="tutorial_MSEA.php" title=""><div>MSEA</div></a></li>
                                    <li><a href="tutorial_Meta.php" title=""><div>Meta MSEA</div></a></li>
                                    <li><a href="tutorial_KDA.php" title=""><div>wKDA</div></a></li>
                                    <li><a href="tutorial_vis.php" title=""><div>Visualization</div></a></li>
                                    <li><a href="tutorial_data.php" title=""><div>Additional Data Types</div></a></li>
                                    <li><a href="tutorial_PharmOmics.php" title=""><div>PharmOmics</div></a></li>
                                </ul>
                            </li>
                           <li><a href="LD_Prune.php"><div>MDF</div></a></li>
                            <li><a href="ssea_GWAS.php"><div>MSEA</div></a></li>
                            <li><a href="metassea.php"><div>Meta-MSEA</div></a></li>
                            <li><a href="kda_Gene_Sets.php"><div>wKDA</div></a></li>
                            <li><a href="PharmOmics/"><div>PharmOmics</div></a></li>
                            <li><a href="contact.html"><div>Contact</div></a></li>
                            <li><a href="Download/"><div>Downloads</div></a></li>


                    -->