    <!-- Document Wrapper
    ============================================= -->
    

        <!-- Header
        ============================================= -->
        <header id="header" class="full-header">

            <div id="header-wrap">

               <div class="containter clearfix" style="padding: 0 30px;">
               <!--If browser is small, change menu into mobile ------------------------------------------>
                <div id="primary-menu-trigger"><i class="icon-reorder"></i></div>

                <!-- Logo
                ============================================= -->
                <div id="logo" style="border-right:0px;">
                    <a href="home.php" class="standard-logo"><img src="include/pictures/logo-title@2x-secondary.png" alt="Mergeomics Logo"></a>
                    
                    <a href="home.php" class="retina-logo"><img src="include/pictures/logo-title@2x-secondary.png" alt="Mergeomics Logo"></a> 
                </div><!-- #logo end -->

                

                <!-- Primary Navigation
                ============================================= -->
            

               
                <nav id="primary-menu">

                   

                        

                        <ul class="sf-js-enabled" style="touch-action: pan-y;">
                            <li><a href="home.php"><div>Home</div></a></li>
                            <li><a href="runmergeomics.php"><div>Run Mergeomics</div></a></li>
                            <li><a href="runpharmomics.php"><div>Run PharmOmics</div></a></li>
                            <li><a href="tutorial.php"><div>Tutorial</div></a>
                                <ul>
                                    <!--<li><a href="#" title=""><div>In production!</div></a></li>-->
                                    <!--<li><a href="tutorial_MDF.php" title=""><div>MDF</div></a></li>-->
                                    <!--<li><a href="tutorial_MSEA.php" title=""><div>MSEA</div></a></li>-->
                                    <!--<li><a href="tutorial_Meta.php" title=""><div>Meta MSEA</div></a></li>-->
                                    <!--<li><a href="tutorial_KDA.php" title=""><div>wKDA</div></a></li>-->
                                    <!--<li><a href="tutorial_vis.php" title=""><div>Visualization</div></a></li>-->
                                    <!--<li><a href="tutorial_data.php" title=""><div>Additional Data Types</div></a></li>-->
                                    <!--<li><a href="tutorial_PharmOmics.php" title=""><div>PharmOmics</div></a></li>-->
                                    <li><a href="tutorial.php" title=""><div>Mergeomics</div></a></li>
                                    <li><a href="tutorial_pharmomics.php" title=""><div>Pharmomics</div></a></li>
                                </ul>
                            </li>
                            <li><a href="samplefiles.php"><div>Resources</div></a>
                                <ul>
                                    <li><a href="samplefiles.php" title=""><div>Sample Files</div></a></li>
                                    <li><a href="sample_output.php" title=""><div>Sample Output</div></a></li>
                                    <li><a href="tools.php" title=""><div>Tools</div></a></li>
                                </ul>
                            </li>
                            <li class="current"><a href="contact.php"><div>Contact</div></a></li>
                        </ul>
                </nav>
          </div>
        </div>
</header>