<head>
<!-- Document Title -->
    <title>Mergeomics | A Web server for Identifying Pathological Pathways, Networks, and Key Regulators via Multidimensional Data Integration</title>

<!-- Font -->

    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,400i,700|Raleway:300,400,500,600,700|Crete+Round:400i" rel="stylesheet" type="text/css" />

<!-- Stylesheets -->

    <link rel="stylesheet" href="include/bootstrap.css" type="text/css"/>
    <link rel="stylesheet" href="include/style.css" type="text/css"/>
    <link rel="stylesheet" href="include/dark.css" type="text/css"/>
    <link rel="stylesheet" href="include/docs.css" type="text/css"/>

    <link rel="stylesheet" href="include/agency.css" type="text/css" />
    <link rel="stylesheet" href="include/font-icons.css" type="text/css" />
    <link rel="stylesheet" href="include/animate.css" type="text/css" />
    <link rel="stylesheet" href="include/magnific-popup.css" type="text/css" />
    <link rel="stylesheet" href="include/responsive.css" type="text/css" />
    <link rel="stylesheet" href="include/running_animation.css" type="text/css"/>

    <link rel="stylesheet" href="include/bs-filestyle.css" type="text/css" />

    <!-- Jquery Scripts -->
    <script type="text/javascript" src="include/js/jquery.js" ></script>

   
</head>
