<!doctype html>
<html lang=''>
<head>
   <meta charset='utf-8'>
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <link rel="stylesheet" href="styles.css">
   <script src="http://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>
   <script src="script.js"></script>
   
   <link rel="icon" 
         type="image/png" 
         href="icon.png">

          
           <META HTTP-EQUIV="Content-Type" CONTENT="text/html;CHARSET=iso-8859-1">
           <META name="description" content="UCSC Genome Browser">
           <META name="keywords" content="genome, genome browser, human genome, genome assembly, Blat, UCSC, 			bioinformatics, gene prediction, SNP, SNPs, EST, mRNA, mouse genome, rat genome, chicken genome, chimp genome, 			dog genome, fruitfly genome, zebrafish genome, xenopus, frog genome, rhesus, opossum, danio rerio genome, 			drosophila, fugu, yeast, ciona,  comparative genomics, human variation, hapMap">
           <TITLE>Mergeomics: An Integrated framework for pathway-based analysis of genome-wide association studies 			Home</TITLE>
           <!-- <LINK REL="STYLESHEET" HREF="style/HGStyle.css"> -->
   			<META name="verify-v1" content="PCwOyGxw6+Ib1t4DtxiRLG45cL2xihRrRVgsqKtIP84=" />
			
	

   
</head>

<BODY BGCOLOR="white" LINK="0000CC" VLINK="#330066" ALINK="#330066">
<A NAME="TOP"></A>


<!-- <TABLE BORDER=0 WIDTH="100%"> 1034px-->
<TABLE align="center" style="margin: 0px auto; width: 1257px">
	<TR>
		<TH width="1034px" COLSPAN=2 ALIGN="left"><IMG SRC="title.jpg" ALT="UCLA IntegrativeOmics Bioinformatics"></TH>
    <TH width="300px"></TH>
	</TR>
</TABLE>

<body>
<!-- <TABLE align="center" style="margin: 0px auto; width: 1000px"> -->

<div id='cssmenu' align="center" style="margin: 0px auto; width: 1113px; position: relative; right: 76px;">

<ul width: 1034px align="left">
   <li><a href='home.php'>Home</a></li>
   <li><a href='tutorial.php'>Tutorial</a><li>
   <li><a href='LD_Prune.php'>Run MDF</a><li>
   <li><a href='ssea.php'>Run MSEA</a></li>
   <li><a href='metassea.php'>Run Meta-MSEA</a></li>
   <li><a href='kdapipeline.php'>Run wKDA</a></li>
   <li><a href='./Download'>Downloads</a></li>
</ul>
</div>

</body>
<html>


</html>